### ISSUE TITLE
can this porject support x86?

### ISSUE THREAD

**Issue by fmj1980** [Extrimis/Win32-Acrylic-Effect#2]

**Comment by Extrimis** [comment]
We are currently working on it. its too complex project, it will take more time, since it uses dwm private api anytime they can change the functions.

**Comment by wangwenx190** [comment]
@fmj1980 What's blocking you from using this repo in x86?

@Extrimis This repo doesn't support x86? I extracted AcrylicCompositor's code into my own project and it can be compiled in x86 mode, but since I personally prefer x64 so I haven't run the x86 executables yet.

**Comment by Extrimis** [comment]
yes you can compile the repo in x86 but while running the` GetProcAddress()` will throw exception, in x86 due to mismatched calling convention.

> Run-Time Check Failure #0 - The value of ESP was not properly saved across a function call.  This is usually a result of calling a function declared with one calling convention with a function pointer declared with a different calling convention.

**Comment by Extrimis** [comment]
> @fmj1980 What's blocking you from using this repo in x86?
> 
> @Extrimis This repo doesn't support x86? I extracted AcrylicCompositor's code into my own project and it can be compiled in x86 mode, but since I personally prefer x64 so I haven't run the x86 executables yet.

is the acrylic missing desktop icons ?

**Comment by Extrimis** [comment]
@wangwenx190 if you are rendering acrylic to a separate window, please make sure that window has no content, if there is something in it, it will flicker a littlebit on resize

**Comment by wangwenx190** [comment]
>
> is the acrylic missing desktop icons ?
>
Yes, but not always. Sometimes the desktop icons are missing indeed. But I haven't found the reason that triggers this bug yet.

>
> if you are rendering acrylic to a separate window, please make sure that window has no content, if there is something in it, it will flicker a littlebit on resize
>
Thanks for your advice! Yes I will not put any content in that window.

>
> yes you can compile the repo in x86 but while running the GetProcAddress() will throw exception, in x86 due to mismatched calling convention.
>
OK, thanks for your detailed explanation!

**Comment by Extrimis** [comment]
The desktop icons is missing because The `SHELLDLL_DefView` is actually detached from progman, and I use progman as the desktop visual source. 

![image](https://user-images.githubusercontent.com/72641365/126102312-00a08302-ab6a-4523-9f41-7ab5de68efd6.png)

I fixed this issue already but I haven't added the code to repo because I actually messed up the existing code. anyway I will add this to the new code that I am working on. do you have discord, slack or telegram if so I will send you the code which I have fixed the desktop icon issue. (you need to clean up the code a little bit, it's a bit messed up).

**Comment by wangwenx190** [comment]
>
> do you have discord, slack or telegram if so I will send you the code which I have fixed the desktop icon issue
>
Thanks! I've just created a discord account and I have joined your server.

**Comment by Extrimis** [comment]
@fmj1980 , I have added the x86 support for the acrylic, please check it out.   #6ed9566
