### ISSUE TITLE
How to exclude a specific window from the Acrylic background?

### ISSUE THREAD

**Issue by wangwenx190** [Extrimis/Win32-Acrylic-Effect#3]
Hi bro, I'm still trying the overlap windows, but I found the foreground window will also become part of the acrylic background, it looks weird, could you please teach me how can I exclude it from the acrylic effect?

Maybe I should use the following variable?

https://github.com/Extrimis/Win32-Acrylic-Effect/blob/4aee11e6eab7fa5257114bfd47ff72d2746a82c2/Acrylic%20Window/AcrylicCompositor.h#L146

**Comment by Extrimis** [comment]
**There are two ways to remove a window from acrylic :**

1. Adding your Window hwnd to `hwndExclusionList`
2.  Excluding window using `SetWindowCompositionAttribute()`


### Using hwndExclusionList

if you want to exclude a particular window from acrylic all you have to do is add the hwnd of that window to `hwndExclusionList`.
check this code :


```
hwndExclusionList = new HWND[1];
hwndExclusionList[0] = (HWND)0x0; // Use your window hwnd here
```
_Note: I haven't tested it yet_

### Using SetWindowCompositionAttribute()
You can also exclude the window using  `SetWindowCompositionAttribute()` by setting `WCA_EXCLUDED_FROM_LIVEPREVIEW`.
see this example : 

```
BOOL enable = TRUE;
WINDOWCOMPOSITIONATTRIBDATA CompositionAttribute{};
CompositionAttribute.Attrib = WCA_EXCLUDED_FROM_LIVEPREVIEW;
CompositionAttribute.pvData = &enable;
CompositionAttribute.cbData = sizeof(BOOL);
DwmSetWindowCompositionAttribute(hwnd, &CompositionAttribute); // Give your window hwnd here
```

_Note: Here I have used functions from my code._

**Comment by wangwenx190** [comment]
Thanks for your quick reply, bro!

I'll try `hwndExclusionList` because the latter one seems not working on my side, still investgating the reason.

**Comment by Extrimis** [comment]
> Thanks for your quick reply, bro!
> 
> I'll try `hwndExclusionList` because the latter one seems not working on my side, still investgating the reason.

Thank you, in the sample I excluded the window with WCA_EXCLUDED_FROM_LIVEPREVIEW itself.

**Comment by Extrimis** [comment]
I am working on a project using this acrylic ,which uses com interfaces so that it can be easily used in any other platforms. (`IAcrylicCompositor` & `IAcrylicWrapper` interfaces)

**Comment by wangwenx190** [comment]
>
> in the sample I excluded the window with WCA_EXCLUDED_FROM_LIVEPREVIEW itself.
>
Yes I saw the code, it's working indeed. But if I tried to do the same thing for my own window, it failed to work. Still investgating ...

>
> so that it can be easily used in any other platforms. 
>
What does this mean? You mean it will work on various Windows versions or it will become cross-platform, such as supporting Linux?

**Comment by Extrimis** [comment]
no not for linux, in windows itself, WPF,win32,QT etc...

The sample code will look like this in c#:

```
[ComImport]
[Guid("21ADD712-EB5B-492F-800C-B45435F527B1")]
[InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
interface IAcrylicCompositor
{
     void enableAcrylic(IntPtr hwnd);
}

[DllImport("AcrylicCompositor.dll")]
static extern bool CreateAcrylicCompositor(out IAcrylicCompositor compositor);
```

and you can call, it easily like this.

```
IAcrylicCompositor compositor = null;
CreateAcrylicCompositor(out compositor);
compositor.sayHello(new WindowInteropHelper(this).EnsureHandle());
```

**Comment by wangwenx190** [comment]
Sounds fantastic! Really look forward to it! But wouldn't there be the airspace issue? Do you solved it or you are using the solution you told me some days ago?

**Comment by wangwenx190** [comment]
>
> i am also working on the Other effects such as noise,blending etc..
>
Can't wait to see your code! Awesome work, bro!

**Comment by Extrimis** [comment]
> > i am also working on the Other effects such as noise,blending etc..
> 
> Can't wait to see your code! Awesome work, bro!

Thank you

**Comment by Extrimis** [comment]
> Sounds fantastic! Really look forward to it! But wouldn't there be the airspace issue? Do you solved it or you are using the solution you told me some days ago?

for the airspace issue i might be using window overlay itself, the other solution works but there is no way to pass events from one window to another. for wpf and all the events are handled by dispatcher and just sharing the wndproc did not work in that case
